# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 236eebc419e03dfd99d46ff2f44628229b2439425dc03a67d9e18ca8d62f17a97778a3d06d938457f8aaec61ce03583a45ab0f1722b0abf156ef9f242f457bac

test:
  secret_key_base: 9bf4d0c20b0b352df89065520a976e0c992abc4f8c2786a2e67f0f22c2beef469253c4347ca61b0d761575428ea068e8ac8790adb8e33cff95587f14f51b7e8a

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
